### ISSUE TITLE
Not able to map project because it is not supported by atlas

### ISSUE THREAD

**Issue by farhaanbukhsh** [EnSoftCorp/call-graph-toolbox#2]
I am trying to run call graph for a project called https://github.com/Alluxio/alluxio, but any time I try to do `Atlas --> Manage Project Setting`, I get to see the dialog box which says cannot map the project because it is not supported by Atlas. I have been trying to figure it out but had no luck.

![image](https://user-images.githubusercontent.com/7670449/52175470-7a491e00-27ca-11e9-969c-406caa0f9b4e.png)

Can you guys help to understand what is going on?

**Comment by benjholla** [comment]
The project shows up in the Manage Project Settings window and the message
is shown when you try to map it? Is there a related stack trace in the
Error Log window? Check Window > Show View... > Error Log. If so can you
paste that?

**Comment by nikhilranade** [comment]
The project cannot be mapped because it does not have a java nature. One way to fix it is to right click on the project and click on Properties. Select and enable "Project Facets". You can then select "Java" as a project Facet and Apply (see image below). This will add java nature to the project and you should be able to map it using Atlas. 
![screen shot 2019-02-04 at 2 24 53 pm](https://user-images.githubusercontent.com/2300131/52235127-d7a3a480-2888-11e9-8ac9-a25808138b1a.png)

**Comment by farhaanbukhsh** [comment]
> The project shows up in the Manage Project Settings window and the message is shown when you try to map it?

No the project doesn't even show in the Manage Project Settings Window

 Is there a related stack trace in the Error Log window? Check Window > Show View... > Error Log. If so can you paste that?
There is no error log trace generated when I perform that action.

**Comment by farhaanbukhsh** [comment]
> The project cannot be mapped because it does not have a java nature. One way to fix it is to right click on the project and click on Properties. Select and enable "Project Facets". You can then select "Java" as a project Facet and Apply (see image below). This will add java nature to the project and you should be able to map it using Atlas.
> ![screen shot 2019-02-04 at 2 24 53 pm](https://user-images.githubusercontent.com/2300131/52235127-d7a3a480-2888-11e9-8ac9-a25808138b1a.png)

This kind of help to figure out that the nature of my project was wrongly interpreted I didn't have "Project Facets" but I had "Project Nature" in eclipse property of project, I changed it to java and then I could see that in the re-map project.

Now even when it is added in the mapped project I can't create the call graph because any file that I open it says this file is not the code map. I tried to remap the project but still the same.

**Comment by farhaanbukhsh** [comment]
The problem was alluxio not be being java nature because it has a lot of different small project in it, so first and foremost thing is to build the project and then import the project as `import -> maven project`, this solved the problem of importing the project and then having the call graph for it.

Thanks team.
